from typing import Protocol
from uuid import UUID

from disappearing_tasks.domain.models import VideoTask


class TaskStore(Protocol):
    """Kontrakt magazynu zadań — implementacja: SqliteTaskStore."""

    async def create(self, task: VideoTask) -> VideoTask: ...

    async def get(self, task_id: UUID) -> VideoTask | None: ...

    async def update(self, task: VideoTask) -> VideoTask: ...

    async def mark_step(self, task_id: UUID, step: int) -> VideoTask | None: ...

    async def mark_completed(self, task_id: UUID) -> VideoTask | None: ...

    async def mark_failed(self, task_id: UUID, error: str) -> VideoTask | None: ...

    async def mark_interrupted(self, task_id: UUID) -> VideoTask | None: ...

    async def list_all(self) -> list[VideoTask]: ...

    async def find_resumable(self) -> list[VideoTask]: ...

    async def claim_for_resume(self, task_id: UUID, worker_id: str) -> VideoTask | None: ...